= Практические упражнения по теме "Системы уравнений"

== Уровень 1: Простой

. Решите систему уравнений методом подстановки:  
```
\begin{cases}
x + 2y = 7 \\
3x - y = 4
\end{cases}
```

. Решите систему уравнений методом сложения:  
```
\begin{cases}
2x + 3y = 12 \\
4x - 3y = 6
\end{cases}
```

. Найдите решение графическим методом (подумайте, как найти точку пересечения без построения графиков):  
```
\begin{cases}
y = x + 2 \\
y = -2x + 5
\end{cases}
```

== Уровень 2: Средний

. Решите систему уравнений методом подстановки:  
```
\begin{cases}
2x - 3y = 1 \\
x + 4y = 9
\end{cases}
```

. Решите систему уравнений методом сложения:  
```
\begin{cases}
5x + 2y = 14 \\
3x - 4y = 2
\end{cases}
```

. Найдите решение системы, используя графический метод, предварительно выразив одну переменную через другую:  
```
\begin{cases}
y = \frac{1}{2}x - 1 \\
y = -x + 4
\end{cases}
```

== Уровень 3: Сложный

. Решите систему уравнений методом подстановки:  
```
\begin{cases}
3x + 5y = 11 \\
7x - 2y = 3
\end{cases}
```

. Решите систему уравнений методом сложения:  
```
\begin{cases}
6x - 4y = 8 \\
9x + 6y = 15
\end{cases}
```

. Исследуйте систему и решите её:  
```
\begin{cases}
2x + 3y = 5 \\
4x + 6y = 10
\end{cases}
```
Определите, имеет ли система одно решение, бесконечно много решений, или решений нет. Обоснуйте свой ответ.

. Решите систему уравнений, используя самый удобный для вас метод:  
```
\begin{cases}
x - y = 3 \\
2x + y = 7
\end{cases}
```

. Для системы  
```
\begin{cases}
x + y = k \\
2x + 2y = 2k + 1
\end{cases}
```
найдите значение параметра \(k\), при котором система не имеет решений.

== Дополнительное задание

. Проверьте свое решение любой системы из вышеуказанных, подставив найденные значения переменных в оба уравнения. Запишите проверку.