= Домашнее задание по теме "Системы уравнений"

Уважаемые ученики! Проверьте свои знания и умения, выполнив задания разного уровня сложности. Постарайтесь использовать изученные методы: подстановки, сложения и графический метод. Не забывайте тщательно проверять свои решения!

== Уровень 1: Простой

:warning: Инструкция: Решите каждую систему уравнений, используя указанный метод. Запишите полный ход решения и ответ.

. Решите систему методом подстановки:  
```
\begin{cases}
x + 2y = 7 \\
3x - y = 4
\end{cases}
```

. Решите систему методом сложения:  
```
\begin{cases}
2x + 3y = 12 \\
4x - 3y = 6
\end{cases}
```

. Найдите решение графическим методом, используя аналитический подход (подумайте как найти точку пересечения, не строя графики):  
```
\begin{cases}
y = x + 2 \\
y = -2x + 5
\end{cases}
```

== Уровень 2: Средний

:dart: Инструкция: Выполните задачи, применяя предложенные методы, или выбирая наиболее удобный способ. Обязательно запишите все этапы решения.

. Решите систему методом подстановки:  
```
\begin{cases}
2x - 3y = 1 \\
x + 4y = 9
\end{cases}
```

. Решите систему методом сложения:  
```
\begin{cases}
5x + 2y = 14 \\
3x - 4y = 2
\end{cases}
```

. Найдите решение системы с помощью графического метода, предварительно выразив одну переменную через другую:  
```
\begin{cases}
y = \frac{1}{2}x - 1 \\
y = -x + 4
\end{cases}
```

== Уровень 3: Сложный

:muscle: Инструкция: Тщательно разберитесь с заданиями, применяйте разные методы, анализируйте систему и причины существования решений или их отсутствия.

. Решите систему методом подстановки:  
```
\begin{cases}
3x + 5y = 11 \\
7x - 2y = 3
\end{cases}
```

. Решите систему методом сложения:  
```
\begin{cases}
6x - 4y = 8 \\
9x + 6y = 15
\end{cases}
```

. Исследуйте систему на число решений и решите её:  
```
\begin{cases}
2x + 3y = 5 \\
4x + 6y = 10
\end{cases}
```
Определите, есть ли одно, бесконечно много или нет решений. Обоснуйте ваш вывод.

. Решите систему, используя самый удобный для вас метод:  
```
\begin{cases}
x - y = 3 \\
2x + y = 7
\end{cases}
```

. Для системы с параметром \(k\):  
```
\begin{cases}
x + y = k \\
2x + 2y = 2k + 1
\end{cases}
```
найдите значение параметра \(k\), при котором система не имеет решений. Объясните свой ответ.

== Дополнительное задание

:star: Выберите любую систему из предыдущих заданий. Проверьте своё решение: подставьте найденные значения переменных в оба уравнения и запишите подробную проверку.

---

Желаю вам успехов и вдохновения! Помните — внимательно выполнять все шаги и проверять результат очень важно. С каждым решённым заданием ваши навыки станут ещё сильнее!