== Упражнения по теме "Степени и корни"

[cols="1,1",options="header"]
|===
| Уровень сложности | Задача

| Легкий
| 1. Вычислите:  
   а) \( 4^3 \)  
   б) \( 10^0 \)  
   в) \( 2^5 \times 2^2 \)  

| Легкий
| 2. Найдите:  
   а) \(\sqrt{49}\)  
   б) \(\sqrt[4]{81}\)  
   в) \(\sqrt[3]{-8}\)  

| Средний
| 3. Упростите выражения:  
   а) \(\frac{7^5}{7^2}\)  
   б) \(\left(5^3\right)^2\)  
   в) \((2 \times 3)^4\)  

| Средний
| 4. Упростите:  
   а) \(\sqrt{16 \times 25}\)  
   б) \(\sqrt{\frac{36}{9}}\)  
   в) \(\sqrt[3]{\sqrt{64}}\)  

| Средний
| 5. Запишите выражение без отрицательных показателей степени:  
   а) \( 4^{-3} \)  
   б) \( \frac{1}{9^{-2}} \)  
   в) \( (2^{-1})^4 \)  

| Сложный
| 6. Вычислите:  
   а) \(\frac{3^7 \times 3^{-2}}{3^3}\)  
   б) \(\left(\frac{2^3}{4^2}\right)^3\)  
   в) \(\sqrt[5]{32^3}\)  

| Сложный
| 7. Упростите выражение и приведите его к виду \(a^n\), где \(a\) — число:  
   а) \(\left(9^{\frac{1}{2}}\right)^4\)  
   б) \(\sqrt[3]{27^2}\)  
   в) \(\frac{(16^{\frac{3}{4}})}{(8^{\frac{2}{3}})}\)  

| Сложный
| 8. Решите уравнение:  
   а) \( x^4 = 81 \)  
   б) \( \sqrt{x} = 5 \)  
   в) \( \sqrt[3]{x^2} = 9 \)  

| Сложный
| 9. Докажите равенство, используя свойства степеней и корней:  
   а) \(\sqrt{a^2} = |a|\)  
   б) \((\sqrt[n]{a})^n = a\)  
   в) \(\sqrt[m]{\sqrt[n]{a}} = \sqrt[m \times n]{a}\)  

| Эксперт
| 10. Исследуйте и упростите выражение:  
   \[
   \frac{\left(2 \sqrt{3}\right)^4}{(6^{\frac{3}{2}})} \times \sqrt[3]{27}
   \]
   Запишите результат в виде степени с целым показателем.

| Эксперт
| 11. Решите уравнение для \(x\), \(x > 0\):  
   \[
   \sqrt[3]{x^2} \times \sqrt{x} = 16
   \]

| Эксперт
| 12. Сравните числа и объясните свой ответ:  
   а) \(\sqrt{50}\) и \(7.1\)  
   б) \(2^{\frac{5}{2}}\) и \(4^{\frac{3}{2}}\)

|===