flowchart TB
    subgraph C["Complex numbers ℂ"]
        direction TB
        subgraph R["Real numbers ℝ"]
            direction TB
            subgraph Q["Rational numbers ℚ"]
                direction TB
                subgraph Z["Integers ℤ"]
                    direction TB
                    subgraph W["Whole numbers (ℕ₀)"]
                        direction TB
                        N["Natural numbers ℕ"]
                    end
                end
            end
            I["Irrational numbers (ℝ ∖ ℚ)"]
        end
    end